linuxdeepin/dde-tray-loader

src/loader/widgetplugin.cpp

return nullptr when popupWidget->windowHandle() is called
Issue:

fix: crash when removing the usb drive

---

src/loader/pluginitem.h
src/loader/quickpluginitem.cpp
src/loader/quickpluginitem.h
src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginmanager.cpp
src/tray-wayland-integration/pluginmanager_p.h
src/tray-wayland-integration/pluginsurface.cpp
src/tray-wayland-integration/pluginsurface_p.h

create surface for global ToolTipWindow, and it's extent property
is from it's transientParent,
and then update it's position in next event loop.

fix: missing tooltip in quickpanel

---

plugins/dde-dock/bluetooth/quickpanelwidget.cpp
plugins/dde-dock/common/singlequickpanel.cpp
plugins/dde-dock/media/quickpanelwidget.cpp
plugins/dde-network-core/dock-tray-network-plugin/quickpanelwidget.cpp
plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/quickpanelwidget.cpp

MouseEvent should be propagated to parent widget if not accept.

fix: missing release event for pluginitem

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp
src/tray-wayland-integration/plugin.cpp

1.plugin panel title disappears after clicking the jumpSetting button 2.first click jumpSetting btn, panel popup does not show when clicking plugin item again
Log: as title
Influence: plugin panel display

fix: plugin panel display error

---

src/loader/quickpluginitem.cpp

MouseRelease is lossed when retray drag icon area, and it's parent
is received the event.

fix: drag only works once when retray drag icon area

---

src/loader/pluginitem.cpp

tooltip don't need following mouse's position.

fix: tooltip position isn't centered

---

plugins/dde-network-core/net-view/window/private/netdelegate.cpp
plugins/dde-network-core/net-view/window/private/netdelegate.h

It's wrong in qt5.15, and ok in qt5.11.
We only want to change centralWidget's palette except NetSecretWidget.

fix: incocrrect highlight palette for network

---

src/loader/pluginitem.cpp

menu not update.
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9761
Influence: menu content display

fix: plugin right-click menu content displays incorrectly

---

plugins/dde-dock/dnd-mode/dndmodeitem.cpp
plugins/dde-dock/power/powerstatuswidget.cpp
plugins/dde-dock/sound/soundapplet.cpp

dbus param error
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9719
Influence: jump dcc module

fix: clicking some plugins setting btn cannot jump to dcc's module

---

plugins/application-tray/util.cpp

Tray plugin loader crashed on launch
Issue: https://github.com/linuxdeepin/developer-center/issues/9667
Log: Check X11 client window existence

fix: Check X11 client window existence

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/quickpluginitem.cpp
src/loader/quickpluginitem.h

Calling dock's dbus to dock or undock, instead of hide or show it's
window.

fix: pinned to dock only works once

---

plugins/dde-dock/datetime/datetimeplugin.cpp

When the position of the taskbar changes, the time control needs to be resized in real time.
Issue: https://github.com/linuxdeepin/developer-center/issues/9688

fix: Fixed the issue  the time control is not fully displayed

---

plugins/dde-network-core/net-view/operation/netitem.cpp

dcc has no airplane module.
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9674
Influence: not jump dcc's airplane module

fix: Disable jumping to dcc's airplane module

---

src/loader/widgetplugin.cpp

Issues: linuxdeepin/developer-center#9820

fix: datetime plugin in DCC dosn't have icon

---

plugins/dde-network-core/net-view/window/netview.cpp

The grabGesture function caused the mouse press event to not be sent to the child control
Issue: https://github.com/linuxdeepin/developer-center/issues/9722

fix: Modify the issue of unresponsive clicks on the network panel

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp
src/tray-wayland-integration/pluginsurface_p.h

as title
Log: as title
Influence: plugin item display

feat: plugin item can set content margin

---

plugins/dde-network-core/net-view/window/netstatus.cpp
src/loader/pluginitem.cpp

After the icon size changed, the parent window size did not change in a timely manner
Issue: https://github.com/linuxdeepin/developer-center/issues/9888

fix: Modifying proxy icon does not display issue

---

plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/xembedprotocolhandler.cpp

wechat and wework has same proc/exe which make them have same id. It will be considered as a registered plugin and call show directly while the plugin does not have a corresponding window actiually.
So appned winId after exe as new id which will distinguishing between different instances of the same programe
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/9918

fix: applicatin-tray coredump while open wechat and wework

---

plugins/dde-dock/airplane-mode/airplanemodeitem.cpp
plugins/dde-dock/common/commonapplet.cpp
plugins/dde-dock/common/commonapplet.h

Also, add hideSettingButton method for CommonApplet class
Issue: https://github.com/linuxdeepin/developer-center/issues/9884 Log:

fix: Hide Airplane mode settings in popup applet

---

plugins/dde-network-core/net-view/operation/netmanager.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9946
Influence: network vpn setting can jump to dcc's vpn module

fix: network vpn setting cannot jump to dcc's vpn module

---

src/loader/pluginitem.cpp
src/tray-wayland-integration/plugin.cpp

Application tray is using custom widget instead of PluginItem's
menu, so we shouldn't show PluginItem's menu, otherwise it maybe
show an empty menu.

fix: menu maybe invalid for app tray

---

src/loader/pluginitem.cpp

Position offset of half the width and height of itemWIdge
Issue: https://github.com/linuxdeepin/developer-center/issues/9953

fix: ToolTip is positioned to the left

---

plugins/dde-dock/dnd-mode/dndmodeitem.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/9988

fix: Fixed dnd-mode settings cannot jump to the Control Center

---

src/loader/quickpluginitem.cpp

plugin doesn't separate left button and right button.
Issue: https://github.com/linuxdeepin/developer-center/issues/9960

fix: right button also emits clicked for quickpanel

---

plugins/dde-dock/bluetooth/componments/bluetoothapplet.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9990
Influence: bluetooth can not jump to dcc's airplane mode

fix: removing jump to dcc's airplane mode

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h

Tooltips require a layer of widget, otherwise there may be issues with size handling
Issue: https://github.com/linuxdeepin/developer-center/issues/10043
Influence: tooltip display

fix: adjust tooltip display

---

plugins/application-tray/xembedprotocolhandler.cpp

Use relative cursor motion event instead
Issue: https://github.com/linuxdeepin/developer-center/issues/9987
Log: Cursor instantly move to left side

fix: Cursor instantly move to left side

---

plugins/dde-dock/bluetooth/componments/bluetoothapplet.cpp

fixed width 330.
Log: fix bluetooth list width bug
Issue: https://github.com/linuxdeepin/developer-center/issues/9981
Influence: bluetooth devices list display

fix: bluetooth devices list width

---

plugins/application-tray/sniprotocolhandler.cpp

Menu grab mouse in server, so it always gets inputforcus.
Issue: https://github.com/linuxdeepin/developer-center/issues/9721
Issue: https://github.com/linuxdeepin/developer-center/issues/9729

fix: Menu display incomplete

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h

use moveEvent to Refresh Position
Issue: https://github.com/linuxdeepin/developer-center/issu es/10096

fix: Popup position cannot be refreshed with dock

---

src/tray-wayland-integration/pluginsurface.cpp

After the PluginPopupSurface object is released, the static function is called to plugin_popuc_lose
Issue: https://github.com/linuxdeepin/developer-center/issues/10118
Issue: https://github.com/linuxdeepin/developer-center/issues/10067

fix: Modify the issue of dock plugin crashing when double clicking

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/quickpluginitem.cpp
src/loader/widgetplugin.cpp

as title.
Log: as title
Influence: left mouse clicking quickItem

fix:  clicking quickItem plugin with the left mouse button donot work

---

plugins/dde-network-core/src/impl/networkmanager/devicemanagerrealize.cpp

When enabling the network, it is necessary to synchronously turn on Autoconnect
Issue: https://github.com/linuxdeepin/developer-center/issues/10184

fix: Modify network non automatic reconnection issue

---

plugins/dde-dock/datetime/regionFormat.cpp

如果长时间格式的dconfig是空的，则设置一个默认值
Issue: https://github.com/linuxdeepin/developer-center/issues/10233

chore: 如果长时间格式的dconfig是空的，则设置一个默认值

---

plugins/application-tray/xembedprotocolhandler.cpp
plugins/application-tray/xembedprotocolhandler.h

Attention may have been triggered during the first loading, resulting in an incorrect icon that was not updated later
Issue: https://github.com/linuxdeepin/developer-center/issues/9819

fix: the enterprise WeChat icon is empty

---

plugins/dde-dock/datetime/datetimewidget.cpp

release 解决显示时间tips的date和time贴在一起的问题
Issue: https://github.com/linuxdeepin/developer-center/issues/10339

chore: 解决显示时间tips的date和time贴在一起的问题

---

plugins/application-tray/xembedprotocolhandler.cpp

Repeated call Manage() cause the application repeatedly call Added and Removed operations.
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10439

fix: adding tray icon blocks app launch

---

src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/pluginsurface.cpp

call destroy to release shellSurface object for server.
Issue: https://github.com/linuxdeepin/developer-center/issues/10121

feat: add destroy protocol

---

plugins/application-tray/traywidget.cpp

avoid displaying empty area due to not obtaining icons.

chore: add fallback icon for applicaiton-tray

---

src/loader/pluginitem.cpp

1.When the dock is on the right, the margins is not 10. 2.tooltip widget resize, 当任务栏在右的时候，窗口变化会会遮住鼠标导致leaveEvent触发，tooltip消失
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10478

fix: tooltip margin and tooltip disappears abnormally

---

plugins/application-tray/util.cpp

treeland x wayland no ewmh support, will crash in ewmh init
log: as title

fix: application tray crash on treeland

---

plugins/dde-dock/media/quickpanelwidget.cpp

Icon size needs to be adapted to screen scale ratio.
Bug: https://pms.uniontech.com/bug-view-272035.html
Log: Music icon is too small in quick panel on High scale ratio screen

fix: Music icon is too small in quick panel on High scale ratio screen

---

plugins/dde-dock/configs/org.deepin.dde.dock.plugin.power.json
plugins/dde-dock/power/powerplugin.cpp
plugins/dde-dock/power/powerplugin.h
src/loader/configs/com.deepin.dde.dock.module.gschema.xml

As title, to adapt to the dde-control-center of deepin 25
Log:

feat: Power module uses DConfig instead of QGSettings

---

plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.cpp
plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.h

Do not display lunar and buttons when the calendar app does not exist Reference: https://gerrit.uniontech.com/c/dde-dock/+/255151
Log: the calendar plugin is abnormal
Bug: https://pms.uniontech.com/bug-view-274789.html

fix: the calendar plugin is abnormal when the calendar app does not exist

---

plugins/application-tray/sniprotocolhandler.cpp

The right-click menu icon of the Sni protocol plugin adapts to the dark theme
Log: right-click menu icon adapts to dark theme
Bug: https://pms.uniontech.com/bug-view-270985.html

fix: right-click menu icon adapts to dark theme

---

plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.cpp

Button hiding does not depend on the locale language
Log: no "Open Calendar" button in non-Chinese environments
Bug: https://pms.uniontech.com/bug-view-277117.html

fix: no "Open Calendar" button in non-Chinese environments

---

plugins/application-tray/sniprotocolhandler.cpp
src/loader/pluginitem.cpp
src/loader/quickpluginitem.cpp
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

QWindow cannot set window position on wayland, and will always return (0,0) So we store plugin pos at EmbedPlugin not in QWindow anymore.
log: as title

fix: plugin popup/tooltip pos not correct

---

debian/changelog
plugins/application-tray/sniprotocolhandler.cpp
src/loader/pluginitem.cpp
src/loader/quickpluginitem.cpp
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

合入cherry-pick的1个fix：
```
* fix: plugin popup/tooltip pos not correct
```
新版本中还附带了1个fix：
```
* feat: Allow plugins sending close quick panel requests
```
更新版本到1.0.5。

Bump version to 1.0.5

---

interfaces/constants.h
plugins/dde-dock/shutdown/shutdownplugin.cpp
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

Add request_shutdown interface to call shutdown applet
Log: support for requeset shutdown

feat: support for requeset shutdown

---

src/tray-wayland-integration/plugin.h

remove Q_DECL_EXPORT, maybe Qt change default.
Log:

fix: cannot build on archlinux

---

plugins/dde-dock/bluetooth/componments/bluetoothadapteritem.cpp
plugins/dde-dock/bluetooth/componments/bluetoothadapteritem.h
plugins/dde-dock/common/pluginitemdelegate.cpp
plugins/dde-dock/common/pluginitemdelegate.h
plugins/dde-dock/eye-comfort-mode/eyecomfortmodeapplet.cpp
plugins/dde-dock/eye-comfort-mode/eyecomfortmodeapplet.h
plugins/dde-dock/power/powerapplet.cpp
plugins/dde-dock/sound/soundapplet.cpp
plugins/dde-dock/sound/soundapplet.h

dde-dock PluginItem is confused with the same name class from src/loader. And this caused unknown behavior of inheritting QWidget as well.
pms: BUG-277621
Log: dde-dock plugins crash on RISC-V platform

fix: dde-dock plugins crash on RISC-V platform

---

debian/changelog

chore: bump to 1.99.6

---

src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/pluginsurface.cpp

Set plugin size by protocol instead of calculating by buffer
log: as title

fix: popup size not right on treeland

---

plugins/dde-dock/common/commoniconbutton.cpp

Unknown load error on plugin items. Use temporary fallback icon instead.
pms: BUG-293455
Log: fix: dnd-mode and airplane mode plugin icon missing under dark theme

fix: dnd-mode and airplane mode plugin icon missing under dark theme

---

plugins/dde-network-display-ui/plugins/common/wirelesscastingmodel.cpp
plugins/dde-network-display-ui/plugins/common/wirelesscastingmodel.h

as title
Log: as title
Bug: BUG-294901

fix: cooperation-networkDisPlay service is not available

---

interfaces/constants.h
plugins/dde-dock/shutdown/shutdownplugin.cpp
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

as title
Log: as title
Bug: BUG-294875

fix: Shutdown plugin miss menu function

---

plugins/application-tray/abstracttrayprotocol.h
plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/traywidget.cpp
plugins/application-tray/traywidget.h
plugins/application-tray/xembedprotocolhandler.cpp

Listen to the external Widget size instead of just the TrayWidget part
log: as title
pms: BUG-290519

fix: click application tray border has no response

---

debian/changelog

chore: bump version 1.99.8

---

src/loader/widgetplugin.cpp

The message events were emitted on all the plugins. By typo maybe?
pms: BUG-295927
Log: Click on clipboard quick item will trigger screenshot plugins too

fix: Click on clipboard quick item will trigger screenshot plugins too

---

plugins/dde-dock/bluetooth/resources/dark/actions/bluetooth_disable_96px.svg
plugins/dde-dock/bluetooth/resources/light/actions/bluetooth_disable_96px.svg

chore: replace bluetooth disable icon

---

debian/changelog
plugins/application-tray/traywidget.cpp
plugins/application-tray/util.cpp
plugins/application-tray/util.h
plugins/application-tray/xcbthread.cpp
plugins/application-tray/xcbthread.h
plugins/application-tray/xembedprotocolhandler.cpp
plugins/application-tray/xembedprotocolhandler.h
src/tray-wayland-integration/pluginmanager.cpp

chore: bump version to 1.0.9

---

plugins/dde-network-core/src/impl/serviceinter/networkinterprocesser.cpp
plugins/dde-network-core/src/networkcontroller.cpp
plugins/dde-network-core/src/networkinter.h

Incorrect service and interface.

fix: proxy can't disable for dock tray

---

debian/changelog
src/loader/pluginmanager.cpp

chore: Temporary disable some plugins for Treeland

---

plugins/application-tray/sniprotocolhandler.cpp

SniTrayProtocolHandler may be destroyed ,but it's conection is
active.

fix: access nullptr when themeType changed

---

src/loader/main.cpp

unset dde-tray-loader's environment.

fix: wrong environment for children process

---

src/loader/CMakeLists.txt
src/loader/dqwaylandplatform.cpp
src/loader/dqwaylandplatform.h
src/loader/main.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginmanagerintegration.cpp
src/tray-wayland-integration/pluginmanagerintegration_p.h

We register platformInterface for qwayland on non x11,
and client's theme settings are set through wayland protocol.
pms: BUG-301149

feat: adapt to qwayland for DPlatformTheme

---

plugins/dde-dock/common/commoniconbutton.cpp

Changing foregroundRole instead of storing color for highlight,
We can also update palette when activeColor changed.
pms: BUG-304339

fix: always showing previous highlight for DCommonIconButton
