linuxdeepin/dde-tray-loader

CMakeLists.txt
dde-dock.pc.in

add dde-dock.pc to compatible to third-party plugins Log:

chore: add dde-dock.pc

---

src/loader/main.cpp
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp
src/loader/widgetplugin.h

as title
Log: as title
Influence: none

chore: modify some code

---

src/loader/main.cpp

as title
Log: as title
Influence: loader can load local dock plugin shell

chore: load dock plugin shell in debug mode

---

src/loader/quickpluginitem.cpp
src/loader/quickpluginitem.h

Get accepted event by children widgets, and send to server.

fix: send accepted mouse event

---

src/loader/main.cpp
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp

fix: can't load v2 plugin

---

src/tray-wayland-integration/pluginsurface.cpp

fix: update popup's position

---

plugins/dde-dock/airplane-mode/CMakeLists.txt
plugins/dde-dock/bluetooth/CMakeLists.txt
plugins/dde-dock/power/CMakeLists.txt
plugins/dde-dock/sound/CMakeLists.txt
plugins/dde-network-core/dock-tray-network-plugin/CMakeLists.txt
plugins/dde-network-display-ui/plugins/CMakeLists.txt
plugins/notification/CMakeLists.txt

as title
Log: as title
Influence: plugin generated directory

chore: modify plugin generated directory

---

CMakeLists.txt
debian/dde-tray-loader.install
environments.h.in
src/loader/CMakeLists.txt
src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

add dcc_icon in the protocol
Log:

chore: add dcc_icon in the protocol

---

src/loader/pluginitem.cpp
src/loader/quickpluginitem.cpp

Menu's exec maybe cause loss a paint event.

fix: display an extension icons for Menu

---

src/loader/widgetplugin.cpp

attribute not menas a new type
log: as title

fix: timedate have a empty on tray

---

src/tray-wayland-integration/pluginsurface.cpp

feat: support to only update width or height

---

debian/control
debian/dde-tray-loader.install
plugins/dde-dock/keyboard-layout/dbusadaptors.cpp
src/loader/CMakeLists.txt
src/loader/configs/com.deepin.dde.dock.module.gschema.xml
src/loader/widgetplugin.cpp

as title
Log: as title
Influence: all plugin item display

fix: some plugin item does not display in tray area

---

src/loader/CMakeLists.txt
src/loader/dockdbusproxy.cpp
src/loader/dockdbusproxy.h
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/quickpluginitem.cpp
src/loader/quickpluginitem.h

chore: set plugin visible

---

src/tray-wayland-integration/pluginsurface.cpp

feat: support to switch surface for multi window

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h

delay create tooltip
log: as title

fix: create empty tooltip during fastmove

---

src/loader/pluginitem.cpp

as title
Log: as title
Influence: dock or undock function

fix: undock or dock abnormal function

---

plugins/dde-dock/airplane-mode/airplanemodeplugin.cpp
plugins/dde-network-core/network-service-plugin/utils/settingconfig.cpp
plugins/dde-network-core/src/configsetting.cpp
plugins/dde-network-core/src/impl/configwatcher.cpp

install path changed.
Log: as title
Influence: network plugin display

fix: network plugin dConfig appId changed.

---

debian/dde-tray-loader.install

chore: install translations for dde-dock

---

debian/rules

chore: add QT_SELECT to rules

---

plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/trayplugin.cpp
src/tray-wayland-integration/plugin.cpp

fix: coredump when application tray recreated

---

debian/changelog
debian/dde-tray-loader.install
src/loader/CMakeLists.txt
src/loader/main.cpp
src/tray-wayland-integration/CMakeLists.txt

chore: bump version to 0.0.1

---

archlinux/PKGBUILD
debian/rules
plugins/CMakeLists.txt
plugins/try-compile/networkmanagerqt.cc

chore: add archlinux build support

---

plugins/application-tray/sniprotocolhandler.cpp

feat: The tray icon can be obtained from iconThemPath interface

---

plugins/dde-dock/power/powerplugin.cpp

Refresh the icon again in loadPlugin
Issue:
- https://github.com/linuxdeepin/developer-center/issues/9706
- https://github.com/linuxdeepin/developer-center/issues/9703
- https://github.com/linuxdeepin/developer-center/issues/9617

fix: battery icon not refreshing at startup

---

src/loader/quickpluginitem.cpp

The menu needs to retrieve data again every time it is displayed
Issue: https://github.com/linuxdeepin/developer-center/issues/9759

fix: The menu needs to retrieve data again every time it is displayed

---

plugins/dde-network-core/dock-tray-network-plugin/networkplugin.cpp
plugins/dde-network-core/net-view/operation/netmanager.cpp
plugins/dde-network-core/net-view/operation/netmanager.h
plugins/dde-network-core/net-view/operation/private/netmanager_p.h
plugins/dde-network-core/net-view/operation/private/netmanagerthreadprivate.cpp
plugins/dde-network-core/net-view/operation/private/netmanagerthreadprivate.h
plugins/dde-network-core/net-view/operation/private/netsecretagentforui.cpp
plugins/dde-network-core/net-view/operation/private/netsecretagentforui.h

The service name should not be associated with the application name
Issue: https://github.com/linuxdeepin/developer-center/issues/9726

fix: Problem with password change pop-up not displaying

---

plugins/dde-network-core/net-view/operation/private/netmanagerthreadprivate.cpp

Responding to proxy change signals
Issue: https://github.com/linuxdeepin/developer-center/issues/9711

fix: Responding to proxy change signals

---

plugins/dde-network-core/dock-tray-network-plugin/translations/dock-network-plugin.ts
plugins/dde-network-core/dock-tray-network-plugin/translations/dock-network-plugin_zh_CN.ts

Issue: https://github.com/linuxdeepin/developer-center/issues/9680
Issue: https://github.com/linuxdeepin/developer-center/issues/9671

fix: Updated taskbar network plug-in translations

---

debian/dde-tray-loader.install
src/loader/CMakeLists.txt
src/loader/generate_translations.sh
src/loader/main.cpp
src/loader/translations/trayplugin-loader.ts
src/loader/translations/trayplugin-loader_es_ES.ts
src/loader/translations/trayplugin-loader_zh_CN.ts

Issue: https://github.com/linuxdeepin/developer-center/issues/9754
Issue: https://github.com/linuxdeepin/developer-center/issues/9685

fix: Added trayplugin-loader translation

---

src/loader/pluginitem.cpp
src/loader/widgetplugin.cpp

fix: changing spacing can't effect plugin's size

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h

fix: tooltip doesn't hide when showing panel

---

src/loader/pluginitem.cpp
src/loader/pluginitem.h

fix: plugin's popup displayed in quickpanel

---

debian/changelog

as title
Log: bump version to 0.0.3

chore: bump version to 0.0.3

---

plugins/dde-network-core/src/networkcontroller.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/9956

fix: Update translation file path

---

plugins/dde-dock/datetime/datetimeplugin.cpp
plugins/dde-dock/datetime/datetimewidget.cpp
plugins/dde-dock/datetime/regionFormat.cpp
plugins/dde-dock/datetime/regionFormat.h

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9717
Issue: https://github.com/linuxdeepin/developer-center/issues/9857
Influence: datetime plugin display

fix: datetime plugin set 24-hour format do not work

---

plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/sniprotocolhandler.h

sni windowId will get 0 sometime, still make application has same id
log: as title

fix: crash on sni

---

plugins/dde-dock/datetime/datetimeplugin.cpp
plugins/dde-dock/datetime/datetimeplugin.h
plugins/dde-dock/datetime/datetimewidget.cpp
plugins/dde-dock/datetime/datetimewidget.h
plugins/dde-dock/datetime/regionFormat.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9914
Influence: datetime plugin display

fix: datetime plugin size is incorrect

---

debian/changelog

bump version to 0.0.4
Log: bump version to 0.0.4

chore: bump version to 0.0.4

---

src/loader/pluginitem.h
src/loader/quickpluginitem.cpp
src/loader/quickpluginitem.h
src/loader/widgetplugin.cpp
src/loader/widgetplugin.h

request isActive state when painting.
Issue: https://github.com/linuxdeepin/developer-center/issues/10020

feat: request isActive state for quickpanel

---

plugins/dde-dock/datetime/datetimewidget.cpp
plugins/dde-dock/datetime/datetimewidget.h

as title
Log: as title
Influence: datetime plugin display

chore: refactor the dateTime plugin display code

---

src/loader/pluginitem.cpp
src/loader/widgetplugin.cpp
src/loader/widgetplugin.h

chore: refact pluginMsg

---

debian/control

chore: provide a high version dde-dock-dev

---

plugins/dde-dock/power/performancemodecontroller.h
src/loader/main.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/10019

fix: Fixed  the power mode initialization dnot get init value

---

plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/sniprotocolhandler.h
plugins/application-tray/util.cpp
plugins/application-tray/util.h
plugins/application-tray/xembedprotocolhandler.cpp
plugins/application-tray/xembedprotocolhandler.h

使用固定规则加后置自增数字
Issues: linuxdeepin/developer-center#9977,
linuxdeepin/developer-center#9972,
linuxdeepin/developer-center#9697

chore: change the method of generating SNI ID and XEMBED ID

---

debian/changelog

bump version to 0.0.5
Log: bump version to 0.0.5

chore: bump version to 0.0.5

---

plugins/dde-dock/datetime/datetimewidget.cpp

as title.
Log: fix bluetooth list width bug
Issue: https://github.com/linuxdeepin/developer-center/issues/10104
Influence: date text display

fix: date text color does not change with theme

---

plugins/dde-network-core/net-view/window/private/netsecretwidget.cpp
plugins/dde-network-core/net-view/window/private/netsecretwidget.h
plugins/dde-network-core/src/impl/netinterface.h
plugins/dde-network-core/src/impl/networkmanager/ipmanager.cpp
plugins/dde-network-core/src/impl/networkmanager/ipmanager.h
plugins/dde-network-core/src/impl/networkmanager/networkdetailnmrealize.cpp
plugins/dde-network-core/src/impl/networkmanager/networkdetailnmrealize.h

Unprocessed signals during IP changes
Issue: https://github.com/linuxdeepin/developer-center/issues/10073

fix: Error in modifying IP address display

---

plugins/dde-dock/datetime/datetimewidget.cpp

as title.
Log: as title
Influence: datetime display

fix: at high PixelRatio, the datetime display is too large

---

plugins/application-tray/sniprotocolhandler.cpp
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginmanager.cpp

modify subMenu's style.
add a fallback for SubPopup.

fix: subMenu can't show

---

debian/changelog

release version 0.0.6
Log: bump version to 0.0.6

chore: bump version to 0.0.6

---

plugins/dde-network-core/net-view/window/netstatus.cpp
plugins/dde-network-core/network-service-plugin/system/networkinitialization.cpp

Use the new DBus interface
Issue: https://github.com/linuxdeepin/developer-center/issues/10018

fix: The DBus service name has been modified

---

plugins/dde-network-core/network-service-plugin/system/networkinitialization.cpp

Translation issue not installed when modifying user acquisition error
Issue: https://github.com/linuxdeepin/developer-center/issues/10018

fix: Translation issue not installed when modifying user acquisition error

---

src/loader/pluginitem.cpp
src/tray-wayland-integration/plugin.cpp
src/tray-wayland-integration/plugin.h

remove the Popup manually.
Issue: https://github.com/linuxdeepin/developer-center/issues/10229

fix: quickpanel show empty if click tray's item

---

src/tray-wayland-integration/pluginmanager.cpp

as title.
Log: as title
Influence: none

chore: removing print too many logs

---

src/loader/main.cpp

as title.
Log: as title
Influence: app crashed has coredump file

fix: app crashed cannot generate coredump file

---

plugins/dde-dock/datetime/regionFormat.cpp
plugins/dde-dock/datetime/regionFormat.h

chore: 时间格式的tips能够跟随时间格式的变化而变化

---

debian/dde-tray-loader.install
plugins/dde-dock/airplane-mode/airplanemodeplugin.cpp
plugins/dde-dock/common/settingmanager.cpp
plugins/dde-dock/datetime/datetimeplugin.cpp
plugins/dde-dock/power/powerplugin.cpp
plugins/dde-dock/shutdown/shutdownplugin.cpp
plugins/dde-dock/sound/soundcontroller.cpp
plugins/dde-network-core/network-service-plugin/utils/settingconfig.cpp
plugins/dde-network-core/src/CMakeLists.txt
plugins/dde-network-core/src/configsetting.cpp
plugins/dde-network-core/src/impl/configwatcher.cpp
src/loader/CMakeLists.txt

fix!: correct app id used by DConfig

---

src/loader/main.cpp

feat: add QT_WAYLAND_RECONNECT=1 env

---

plugins/dde-dock/power/CMakeLists.txt
plugins/dde-dock/sound/CMakeLists.txt
src/loader/CMakeLists.txt

fix: correct DConfig appid name

---

debian/control

fix: conflict with dock-onboard-plugin

---

debian/changelog

bump version to 0.0.7
Log: bump version to 0.0.7

chore: bump version to 0.0.7

---

debian/changelog

bump version to 0.0.8
Log: bump version to 0.0.8

chore: bump version to 0.0.8

---

plugins/dde-dock/eye-comfort-mode/eyecomfortmodeitem.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/10336

fix: Fixed the right-click display settings cannot jump to control center

---

plugins/dde-dock/airplane-mode/airplanemodeitem.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/10335

fix: Remove the Airplane Mode setting option from the Control Center

---

src/loader/pluginitem.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10361

fix: tooltip content cannot update

---

plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/wirelesscastingapplet.cpp

Cancel using color palette to set transparency
Issue: https://github.com/linuxdeepin/developer-center/issues/10106

fix: the text color is incorrect

---

debian/changelog

bump version to 0.0.10
Log: bump version to 0.0.10

chore: bump version to 0.0.10

---

.tx/transifex.yaml

chore: config file format error

---

debian/changelog

bump version to 0.0.11
Log: bump version to 0.0.11

chore: bump version to 0.0.11

---

plugins/dde-dock/power/performancemodecontroller.h

Issue: https://github.com/linuxdeepin/developer-center/issues/10112

fix: Updated ordering of performance modes for power supplies

---

plugins/dde-network-core/dock-tray-network-plugin/translations/dock-network-plugin_zh_CN.ts
plugins/dde-network-core/dock-tray-network-plugin/translations/dock-network-plugin_zh_HK.ts
plugins/dde-network-core/dock-tray-network-plugin/translations/dock-network-plugin_zh_TW.ts

Synchronized network translation
Issue: https://github.com/linuxdeepin/developer-center/issues/10066

fix: Synchronized network translation

---

plugins/application-tray/sniprotocolhandler.cpp
plugins/application-tray/sniprotocolhandler.h
plugins/application-tray/traywidget.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10144

fix: sni protocol item has no icon

---

src/loader/translations/trayplugin-loader.ts
src/loader/translations/trayplugin-loader_ca.ts
src/loader/translations/trayplugin-loader_de.ts
src/loader/translations/trayplugin-loader_de_DE.ts
src/loader/translations/trayplugin-loader_es_ES.ts
src/loader/translations/trayplugin-loader_fi.ts
src/loader/translations/trayplugin-loader_hu.ts
src/loader/translations/trayplugin-loader_nl.ts
src/loader/translations/trayplugin-loader_pl.ts
src/loader/translations/trayplugin-loader_pt_BR.ts
src/loader/translations/trayplugin-loader_sq.ts
src/loader/translations/trayplugin-loader_uk.ts
src/loader/translations/trayplugin-loader_zh_CN.ts

chore: update translation

---

CMakeLists.txt
dde-dock.pc.in
dde-tray-loader.pc.in

log: fix build for deepin-system-monitor

feat: set version for dde-dock.pc

---

debian/changelog

chore: bump version to 0.0.12

---

src/loader/pluginitem.cpp

tweak the font size of plugins'tooltips
Issue: https://pms.uniontech.com/bug-view-271689.html

fix: tooltip style is inconsistent

---

debian/changelog

chore: Bump version to 1.0.1

---

src/loader/pluginitem.cpp

style:  Adjust pointer spacing in moveEvent declaration

---

plugins/dde-dock/sound/soundapplet.h

remove useless function 

---

debian/changelog

release 1.0.2
Log: bump version to 1.0.2

chore: bump version to 1.0.2

---

src/loader/main.cpp
src/loader/quickpluginitem.cpp
src/loader/widgetplugin.cpp
src/loader/widgetplugin.h

chore: fix code style problem

---

src/loader/main.cpp

fix: build failed

---

plugins/dde-dock/notification/CMakeLists.txt
plugins/dde-dock/notification/notificationplugin.cpp

as title.
task: https://pms.uniontech.com/story-view-35599.html

feat: support switching new and old notification

---

plugins/dde-dock/notification/notification.cpp
plugins/dde-dock/notification/notification.h
plugins/dde-dock/notification/notificationplugin.cpp

new notification changes the signal name.
task: https://pms.uniontech.com/task-view-365219.html

fix: notification number doesn't change

---

plugins/dde-dock/datetime/datetimewidget.cpp

wrong time formmat when dock position is left or right
Bug: https://pms.uniontech.com/bug-view-276707.html
Log:

fix: wrong time format

---

plugins/dde-dock/notification/notification.cpp
plugins/dde-dock/notification/notification.h
plugins/dde-dock/notification/notification.qrc
plugins/dde-dock/notification/notificationplugin.cpp

as title.
task: https://pms.uniontech.com/task-view-365893.html

feat: switching icon when notification status changed

---

debian/changelog

chore: bump dev version 1.0.1

---

debian/changelog

release 1.0.4
Log: bump version to 1.0.4

chore: bump version to 1.0.4

---

src/loader/widgetplugin.cpp
src/protocol/plugin-manager-v1.xml
src/tray-wayland-integration/plugin.h
src/tray-wayland-integration/pluginsurface.cpp

Bug: https://pms.uniontech.com/bug-view-272277.html Log:

feat: Allow plugins sending close quick panel requests

---

debian/changelog

chore: bump dev version 1.99.2

---

debian/changelog

chore: wrong format of changelog

---

debian/changelog

chore: Bump version to 1.0.6

---

debian/changelog

chore: bump to 1.99.4

---

plugins/dde-dock/bluetooth/componments/bluetoothapplet.cpp

as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-284405.html

fix: Bluetooth list mouse left click does not work

---

plugins/dde-dock/bluetooth/bluetoothitem.cpp

as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-289763.html

fix: can not jump to dcc bluetooth page

---

src/loader/CMakeLists.txt
src/loader/main.cpp
src/loader/pluginmanager.cpp
src/loader/pluginmanager.h
src/loader/widgetplugin.cpp
src/loader/widgetplugin.h

as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-283901.html

fix: Support loading multiple plugins

---

plugins/dde-network-core/net-view/operation/private/netmanagerthreadprivate.cpp

Always maintain network connectivity status
Log:
pms: BUG-286493

fix: Always maintain network connectivity status

---

debian/changelog

chore: bump to 1.99.7

---

plugins/dde-dock/datetime/calendar/lunarmanager.cpp
plugins/dde-dock/datetime/calendar/lunarmanager.h
plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.cpp
src/loader/main.cpp

Invoking the calendar service through an asynchronous interface
pms: Bug-294455

fix: calendar service connection failed

---

src/tray-wayland-integration/pluginmanagerintegration.cpp

fix: submenu position not right

---

debian/changelog

chore: bump to 1.99.8

---

plugins/dde-network-core/net-view/operation/private/netmanagerthreadprivate.cpp

Network jump command error
Log:
pms: BUG-286767

fix: Network jump command error

---

debian/changelog

chore: bump version to 1.99.10

---

plugins/dde-dock/datetime/datetimeplugin.cpp
plugins/dde-dock/datetime/datetimewidget.cpp
src/loader/pluginitem.cpp
src/loader/pluginitem.h
src/loader/widgetplugin.cpp

1. fix datetime plugin hover display when the dock is minimum
2. calculate the size of datetime plugin when the dock change size
Log: Datetime plugin display problem
Bug: https://pms.uniontech.com/bug-view-276275.html

fix: Datetime plugin display problem

---

debian/changelog

chore: bump version to 1.99.11

---

plugins/application-tray/traywidget.cpp
plugins/application-tray/util.cpp
plugins/application-tray/util.h
plugins/application-tray/xcbthread.cpp
plugins/application-tray/xcbthread.h
plugins/application-tray/xembedprotocolhandler.cpp
plugins/application-tray/xembedprotocolhandler.h

make x embed tray icon size to 1
log: as title

fix: small black block when there is no compositor

---

plugins/dde-dock/bluetooth/componments/bluetoothadapteritem.cpp

fix: access nullptr when switching bluetooth repeated

---

debian/changelog

chore: bump version 1.99.13

---

plugins/dde-network-core/network-service-plugin/accountnetwork/session/accountnetwork/networkactivator.cpp
plugins/dde-network-core/src/impl/networkmanager/devicemanagerrealize.cpp
plugins/dde-network-core/src/impl/networkmanager/vpncontrollernm.cpp

fix: Pop up authentication box

---

debian/changelog

chore: bump version to 1.99.14

---

plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.cpp
plugins/dde-dock/datetime/calendar/sidebarcalendarwidget.h

Adjust size of IconButton, and remove flat flag according by
UI designer.
pms:BUG-289111

fix: missing hover background for datetime plugin

---

debian/changelog

chore: bump version to 1.99.15

---

plugins/dde-dock/shutdown/shutdownplugin.cpp

as title
Log: as title
Pms: BUG-305543

fix: Hibernate menu item cannot be hidden

---

plugins/dde-dock/airplane-mode/airplanemodeitem.cpp

as title
Log: as title
Pms: BUG-286495

fix: airplane mode is not displayed

---

debian/changelog

chore: bump version to 1.99.16

---

src/loader/translations/trayplugin-loader_zh_CN.ts

as title
Log: as title
Pms: BUG-294885

fix: modify tr of "remove from dock"

---

debian/changelog

chore: bump version to 1.99.17

---

plugins/dde-dock/datetime/datetimeplugin.cpp

as title
Log: as title
Pms: BUG-299369

fix: dateTime plugin menu function invalid

---

plugins/dde-dock/datetime/datetimewidget.cpp
plugins/dde-dock/datetime/datetimewidget.h

as title
Log: as title
Pms: BUG-302039

fix: dateTime plugin's hover background height is too high

---

debian/changelog

chore: bump version to 1.99.18

---

plugins/dde-dock/power/powerapplet.cpp
plugins/dde-dock/power/powerapplet.h

as title
Log: as title
Pms: bug-303973

fix: power popup icon size is too small

---

debian/changelog

chore: bump version to 1.99.19

---

plugins/dde-network-display-ui/plugins/CMakeLists.txt
plugins/dde-network-display-ui/plugins/common/wirelesscastingmodel.cpp
plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/wirelesscastingapplet.cpp
plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/wirelesscastingapplet.h
plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/wirelesscastingitem.cpp
plugins/dde-network-display-ui/plugins/dock-wirelesscasting-plugin/src/wirelesscastingitem.h

as title
Log: as title
Pms: bug-307843

chore: remove wireless casting module
